version: "3.5"

volumes:
  masternode:

services:
  mn:
    build:
      context: .
      dockerfile: Dockerfile.masternode
    command: ['/app/mnentrypoint.sh']
    ports:
      - "0.0.0.0:51473:51473"
      - "0.0.0.0:51472:51472"
    volumes:
      - ./mnentrypoint.sh:/app/mnentrypoint.sh
      - ./masternode:/app/.plutus
    restart: always